#!/bin/sh
# XLSH default startup script for X11.
TERMINAL=xterm
XRESFILE=/etc/xlsh/Xresources
BGCOLOR="rgb:1E/23/1F"

screen_w=$(xwininfo -root | grep Width | cut -f2 -d':')
screen_h=$(xwininfo -root | grep Height | cut -f2 -d':')
px=$(($screen_w/2 - 240))
py=$(($screen_h/2 - 120))

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin
export PATH
if ! which xlsh; then
  xmessage -center 'xlsh cannot be found in PATH!'
  exit 1
fi
xrdb -merge "$XRESFILE"
xsetroot -solid "$BGCOLOR"
exec $TERMINAL -g 80x15+$px+$py $(which xlsh)
