#!/bin/sh
# XLSH default startup script for X11.
TERMINAL=xterm
XRESFILE=/etc/xlsh/Xresources
BGCOLOR="rgb:1E/23/1F"

screen_w=$(xwininfo -root | grep Width | cut -f2 -d':')
screen_h=$(xwininfo -root | grep Height | cut -f2 -d':')
px=$(($screen_w/2 - 240))
py=$(($screen_h/2 - 120))

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin
export PATH
if ! which xlsh; then
  xmessage -center "xlsh cannot be found in PATH!"
  exit 1
fi

xrdb -merge "$XRESFILE"
xsetroot -solid "$BGCOLOR"
if which xdotool; then
  # There's a race condition to completion between this job focusing
  # the login window and this script's exec spawning it. Hence the loop.
  err=0
  while :
  do
    if xwindow=$(xdotool search --sync --class "$TERMINAL")
    then
      if xdotool windowfocus --sync "$xwindow"
      then break # success
      fi
    fi
    err=`expr $err + 1`
    if [ $err -gt 10 ]
    then
      xmessage "$0: can't focus xlsh, exceeded retry count"
      break
    fi
    sleep 1
  done &
else
  echo >&2 "$0: no xdotool"
fi
exec $TERMINAL -g 80x15+$px+$py -e $(which xlsh)
